server {
    listen 80;
    server_name ${BACKEND_HOST} www.${BACKEND_HOST};

    root /var/www/html;
    index index.php index.html index.htm;

    access_log /var/log/nginx/access.log main;
    error_log  /var/log/nginx/error.log debug;

    location @opencart {
        rewrite ^/(.+)$ /index.php?_route_=$1 last;
        root      /var/www/html;
    }

    location / {
        root      /var/www/html;
        try_files $uri $uri/ @opencart;
        location ~ [^/]\.ph(p\d*|tml)$ {
            try_files /does_not_exists @php;
        }
        location ~* ^.+\.(jpg|jpeg|gif|png|svg|js|css|mp3|ogg|mpe?g|avi|zip|gz|bz2?|rar|swf|webp|woff|woff2)$ {
            expires 24h;
        }

    }

    location @php {
        root          /var/www/html;
        include       fastcgi_params;

        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_read_timeout 86400;
        fastcgi_send_timeout 86400;
        fastcgi_connect_timeout 86400;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        send_timeout 86400;

        try_files $uri =404;
    }
}
