log_errors = On
error_log = /proc/self/fd/2
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
upload_max_filesize = 2048M
post_max_size = 2048M
memory_limit = 1G
max_execution_time = 0
error_log = /var/log/php/php_errors.log